/**
 * agentIPS.ts
 *
 * IPS Generator Agent — produces a formal Investment Policy Statement document.
 *
 * Uses Gemini to write the prose sections (objective, constraints, risk parameters,
 * asset location summary, executive summary). All structured fields (allocation
 * table, benchmark comparisons, tax alpha calculation, critic score) are assembled
 * deterministically from prior agent outputs.
 *
 * Model: gemini-2.5-flash
 * Expected latency: 2–4 seconds (runs in parallel with agent7_synthesis)
 * Requires: GEMINI_API_KEY environment variable
 *
 * Returns null when the API key is absent or the call fails — the route then
 * omits the ips field from the V3Plan and emits no 'ips' stream event.
 */

import { GoogleGenAI, ThinkingLevel, Type } from '@google/genai';
import { ETF_BY_TICKER } from '@/lib/data/etfUniverse';
import type { IPSDocument, IPSTargetAllocation } from '@/types/index';
import type {
  Agent1Output,
  Agent3Output,
  Agent5Output,
  Agent6Output,
  IntakeAnswers,
} from './types';

const DISCLAIMER =
  'This Investment Policy Statement is generated by an automated algorithm and does not ' +
  'constitute fiduciary investment advice. It is provided for informational and planning ' +
  'purposes only. Past performance is not indicative of future results. Consult a ' +
  'registered investment adviser (RIA) before acting on any recommendation. ' +
  'Investment Advisers Act of 1940, 15 U.S.C. §80b-2(a)(11).';

// VT (Vanguard Total World) CMA benchmarks used for return / Sharpe comparisons
const VT_EXPECTED_RETURN = 0.072;
const VT_SHARPE_ESTIMATE = 0.22;

// ─── Gemini response schema (prose fields only) ───────────────────────────────

const NARRATIVE_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    investmentObjective: {
      type: Type.STRING,
      description:
        '1-2 sentences. Specific — include actual dollar goal, time horizon, and success ' +
        'probability where available. E.g. "Build $1.2M over 22 years targeting 73% success ' +
        'probability, pursuing financial independence through diversified equity growth."',
    },
    liquidityRequirement: {
      type: Type.STRING,
      description:
        '1 sentence. State the required cash reserve based on the client\'s emergency fund ' +
        'status and any planned large expense. Reference actual months or dollars.',
    },
    taxConsiderations: {
      type: Type.STRING,
      description:
        '1-2 sentences. Summarize the client\'s key tax situation: combined marginal rate, ' +
        'state, muni bond suitability, and NIIT exposure if applicable.',
    },
    rebalancingPolicy: {
      type: Type.STRING,
      description:
        '1 sentence. Drift threshold for rebalancing and minimum frequency. ' +
        'E.g. "Rebalance when any holding drifts more than 5% from target; review annually at minimum."',
    },
    reviewSchedule: {
      type: Type.STRING,
      description:
        '1 sentence. Annual review cadence plus triggers for out-of-cycle review ' +
        '(major life event, market drop >20%, income change).',
    },
    maxDrawdownTolerance: {
      type: Type.STRING,
      description:
        '1 sentence. Reference the estimated max drawdown from the portfolio statistics. ' +
        'E.g. "Estimated maximum peak-to-trough drawdown of −28% based on 2008-type stress scenario."',
    },
    concentrationLimit: {
      type: Type.STRING,
      description:
        '1 sentence. Per-position concentration limit inferred from the portfolio. ' +
        'E.g. "No single position exceeds 35% of the portfolio."',
    },
    sequenceRisk: {
      type: Type.STRING,
      description:
        '1 sentence. Sequence-of-returns risk context given the time horizon. ' +
        'For long horizons (>15 years), note low sequence risk; for short (<5 years), flag it.',
    },
    expectedVolatilityNote: {
      type: Type.STRING,
      description:
        '1 sentence. State expected annualized volatility and what a typical drawdown year implies. ' +
        'E.g. "Expected annualized volatility of 14.2% implies a typical bad year of approximately −14%."',
    },
    assetLocationSummary: {
      type: Type.STRING,
      description:
        '2-3 sentences. Summarize the tax-location strategy: which ETFs go in taxable, ' +
        'Roth, traditional/401k — and why. Reference actual tickers and account types.',
    },
    executiveSummary: {
      type: Type.STRING,
      description:
        '2-3 sentences. Overall IPS summary for this client. Cover: risk posture, key tax advantage, ' +
        'goal feasibility verdict, and Critic score interpretation. Reference actual numbers.',
    },
  },
  required: [
    'investmentObjective',
    'liquidityRequirement',
    'taxConsiderations',
    'rebalancingPolicy',
    'reviewSchedule',
    'maxDrawdownTolerance',
    'concentrationLimit',
    'sequenceRisk',
    'expectedVolatilityNote',
    'assetLocationSummary',
    'executiveSummary',
  ],
};

type IPSNarrative = {
  investmentObjective: string;
  liquidityRequirement: string;
  taxConsiderations: string;
  rebalancingPolicy: string;
  reviewSchedule: string;
  maxDrawdownTolerance: string;
  concentrationLimit: string;
  sequenceRisk: string;
  expectedVolatilityNote: string;
  assetLocationSummary: string;
  executiveSummary: string;
};

// ─── Deterministic helpers ────────────────────────────────────────────────────

const BUCKET_DISPLAY: Record<string, string> = {
  safety:      'Safety / Cash',
  growth:      'Growth / Equity',
  income:      'Income / Fixed Income',
  alternative: 'Alternatives / Real Assets',
};

const BUCKET_ORDER = ['safety', 'growth', 'income', 'alternative'];

function buildTargetAllocation(portfolio: Agent3Output): IPSTargetAllocation[] {
  const groups: Record<string, typeof portfolio.allocation> = {};
  for (const slice of portfolio.allocation) {
    if (!groups[slice.category]) groups[slice.category] = [];
    groups[slice.category].push(slice);
  }

  const result: IPSTargetAllocation[] = [];
  for (const cat of BUCKET_ORDER) {
    const slices = groups[cat];
    if (!slices || slices.length === 0) continue;

    const totalWeight = slices.reduce((s, x) => s + x.weight, 0);
    const targetPct = Math.round(totalWeight * 100);

    result.push({
      bucketName: BUCKET_DISPLAY[cat] ?? cat,
      targetPct,
      rangeLow:  Math.max(0, targetPct - 5),
      rangeHigh: Math.min(100, targetPct + 5),
      holdings: slices.map(s => ({
        ticker:           s.ticker,
        name:             ETF_BY_TICKER[s.ticker]?.name ?? s.ticker,
        weight:           Math.round(s.weight * 1000) / 10,
        accountPlacement: s.accountPlacement,
      })),
    });
  }

  return result;
}

// ─── Prompt builder ───────────────────────────────────────────────────────────

function buildPrompt(input: {
  clientProfile:   Agent1Output;
  portfolio:       Agent3Output;
  taxOptimization: Agent5Output;
  criticScore:     Agent6Output;
  intakeAnswers:   IntakeAnswers;
}): string {
  const { clientProfile, portfolio, taxOptimization, criticScore, intakeAnswers } = input;
  const rf = clientProfile.riskProfile;
  const tx = clientProfile.taxProfile;
  const th = clientProfile.timeHorizon;
  const goal = clientProfile.goalAnalysis;
  const stats = portfolio.statistics;

  const holdingsSummary = portfolio.allocation
    .map(s =>
      `  ${s.ticker.padEnd(6)} ${(s.weight * 100).toFixed(1).padStart(5)}%  [${s.category}] → ${s.accountPlacement}`
    )
    .join('\n');

  const topTaxRecs = taxOptimization.recommendations
    .filter(r => r.priority === 'high')
    .slice(0, 4)
    .map(r => `  • ${r.title}: ${r.detail}`)
    .join('\n') || '  None flagged.';

  const restrictions: string[] = [];
  if (clientProfile.investmentPreferences?.esgOnly) restrictions.push('ESG-screened only');
  if (clientProfile.investmentPreferences?.avoidedSectors)
    restrictions.push(`Avoid: ${clientProfile.investmentPreferences.avoidedSectors}`);

  return `You are writing an Investment Policy Statement (IPS) for a specific client.
Write concise, professional prose. No generic disclaimers — reference actual numbers and tickers.

CLIENT PROFILE
══════════════
Risk:          ${rf.riskScore}/10 — ${rf.effectiveRiskTolerance}
Horizon:       ${th.yearsToGoal} years (${th.bucket})${th.isNearDrawdown ? ' — NEAR DRAWDOWN' : ''}
Goal:          ${intakeAnswers.goal}${goal.goalAmount ? ` | target $${goal.goalAmount.toLocaleString()}` : ''}
Feasibility:   ${goal.feasibility} (${(goal.fundedStatus * 100).toFixed(0)}% funded)
Capital:       $${clientProfile.startingCapital.toLocaleString()} lump + $${clientProfile.monthlyContribution.toLocaleString()}/mo
Tax:           ${(tx.federalMarginalRate * 100).toFixed(0)}% federal + ${(tx.stateMarginalRate * 100).toFixed(0)}% state = ${(tx.combinedMarginalRate * 100).toFixed(0)}% combined
State:         ${intakeAnswers.state}
Filing:        ${intakeAnswers.filingStatus}
Accounts:      ${clientProfile.accountStructure.availableAccounts.join(', ')}
Restrictions:  ${restrictions.length > 0 ? restrictions.join('; ') : 'none'}

PORTFOLIO — ${portfolio.allocation.length} ETFs, Sharpe-optimised
══════════════════════════════════════════
${holdingsSummary}

Statistics:
  Expected return:    ${(stats.expectedReturn * 100).toFixed(2)}%
  Expected vol:       ${(stats.expectedVolatility * 100).toFixed(2)}%
  Sharpe ratio:       ${stats.sharpeRatio.toFixed(2)}
  Max drawdown est:   −${(stats.maxDrawdownEstimate * 100).toFixed(1)}%
  Weighted ER:        ${(stats.weightedExpenseRatio * 100).toFixed(3)}%

TOP TAX ACTIONS
═══════════════
${topTaxRecs}
Estimated annual savings: ${taxOptimization.estimatedAnnualSavings} bps

CRITIC SCORE: ${criticScore.scores.overall}/100
  Alignment: ${criticScore.scores.alignment} | Diversification: ${criticScore.scores.diversification} | Tax: ${criticScore.scores.taxEfficiency} | Cost: ${criticScore.scores.costEfficiency} | Risk: ${criticScore.scores.riskManagement}

Write the IPS prose fields for this specific client. Each must reference actual numbers from above.`;
}

// ─── Main agent function ──────────────────────────────────────────────────────

export async function agentIPS(input: {
  clientProfile:   Agent1Output;
  portfolio:       Agent3Output;
  taxOptimization: Agent5Output;
  criticScore:     Agent6Output;
  intakeAnswers:   IntakeAnswers;
}): Promise<IPSDocument | null> {
  const apiKey = process.env.GEMINI_API_KEY ?? process.env.API_KEY;
  if (!apiKey) {
    console.warn('[agentIPS] GEMINI_API_KEY not set — skipping IPS generation');
    return null;
  }

  const { clientProfile, portfolio, taxOptimization, criticScore, intakeAnswers } = input;
  const tx = clientProfile.taxProfile;

  try {
    const ai = new GoogleGenAI({ apiKey });

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: buildPrompt(input),
      config: {
        temperature: 0.2,
        thinkingConfig: { thinkingLevel: ThinkingLevel.LOW },
        responseMimeType: 'application/json',
        responseSchema: NARRATIVE_SCHEMA,
      },
    });

    const jsonText = (response.text ?? '').trim();
    if (!jsonText) return null;

    const narrative = JSON.parse(jsonText) as IPSNarrative;

    // ── Deterministic fields assembled from prior agent outputs ──────────────
    const muniBondSuitable = tx.combinedMarginalRate >= 0.22;

    const rothConversionOpportunity =
      tx.combinedMarginalRate < 0.22 &&
      clientProfile.accountStructure.availableAccounts.some(a =>
        a.toLowerCase().includes('traditional') || a.toLowerCase().includes('401')
      );

    // Convert bps savings to estimated annual dollars
    const annualAUM = clientProfile.startingCapital + clientProfile.monthlyContribution * 12;
    const estimatedAnnualTaxAlpha = Math.round(
      (taxOptimization.estimatedAnnualSavings / 10000) * annualAUM
    );

    const restrictions: string[] = [];
    if (clientProfile.investmentPreferences?.esgOnly) restrictions.push('ESG-screened funds only');
    if (clientProfile.investmentPreferences?.avoidedSectors)
      restrictions.push(`Excluded sectors: ${clientProfile.investmentPreferences.avoidedSectors}`);
    if (clientProfile.investmentPreferences?.favoredSectors)
      restrictions.push(`Tilts toward: ${clientProfile.investmentPreferences.favoredSectors}`);

    const ips: IPSDocument = {
      generatedDate: new Date().toISOString(),

      clientProfile: {
        riskScore:             clientProfile.riskProfile.riskScore,
        derivedRiskTolerance:  clientProfile.riskProfile.effectiveRiskTolerance,
        effectiveMarginalRate: tx.combinedMarginalRate,
        horizon:               clientProfile.timeHorizon.yearsToGoal,
        state:                 intakeAnswers.state,
        filingStatus:          intakeAnswers.filingStatus,
        primaryGoal:           intakeAnswers.goal,
        goalAmount:            intakeAnswers.goalAmount,
      },

      investmentObjective: narrative.investmentObjective,

      constraints: {
        liquidityRequirement: narrative.liquidityRequirement,
        taxConsiderations:    narrative.taxConsiderations,
        restrictions,
        rebalancingPolicy:    narrative.rebalancingPolicy,
        reviewSchedule:       narrative.reviewSchedule,
      },

      targetAllocation: buildTargetAllocation(portfolio),

      riskParameters: {
        maxDrawdownTolerance: narrative.maxDrawdownTolerance,
        concentrationLimit:   narrative.concentrationLimit,
        sequenceRisk:         narrative.sequenceRisk,
        expectedVolatility:   narrative.expectedVolatilityNote,
      },

      taxStrategy: {
        assetLocationSummary:       narrative.assetLocationSummary,
        keyTaxActions:              taxOptimization.recommendations
          .filter(r => r.priority === 'high')
          .map(r => r.title),
        estimatedAnnualTaxAlpha,
        rothConversionOpportunity,
        muniBondSuitable,
      },

      benchmarks: {
        primary:                   'VT (Vanguard Total World ETF)',
        secondary:                 'VBINX (Vanguard Balanced Index Fund)',
        expectedReturnVsBenchmark: Math.round(
          (portfolio.statistics.expectedReturn - VT_EXPECTED_RETURN) * 10000
        ) / 100,
        sharpeVsBenchmark: Math.round(
          (portfolio.statistics.sharpeRatio - VT_SHARPE_ESTIMATE) * 100
        ) / 100,
      },

      executiveSummary: narrative.executiveSummary,
      criticScore:      criticScore.scores.overall,
      disclaimer:       DISCLAIMER,
    };

    return ips;
  } catch (e) {
    console.error('[agentIPS] IPS generation failed:', e);
    return null;
  }
}
