/**
 * agentIPS.ts
 *
 * IPS Generator Agent — produces a formal Investment Policy Statement document.
 *
 * Uses Gemini to write the prose sections (objective, constraints, risk parameters,
 * asset location summary, executive summary). All structured fields (allocation
 * table, benchmark comparisons, tax alpha calculation, critic score) are assembled
 * deterministically from prior agent outputs.
 *
 * Model: gemini-2.5-flash
 * Expected latency: 2–4 seconds (runs in parallel with agent7_synthesis)
 * Requires: GEMINI_API_KEY environment variable
 *
 * Returns null when the API key is absent or the call fails — the route then
 * omits the ips field from the V3Plan and emits no 'ips' stream event.
 */

import { GoogleGenAI, ThinkingLevel, Type } from '@google/genai';
import { trace, SpanStatusCode } from '@opentelemetry/api';
import { ETF_BY_TICKER } from '@/lib/data/etfUniverse';

const tracer = trace.getTracer('agent-ips', '1.0.0');
import type { IPSDocument, IPSTargetAllocation } from '@/types/index';
import type {
  Agent1Output,
  Agent3Output,
  Agent5Output,
  Agent6Output,
  IntakeAnswers,
} from './types';

const DISCLAIMER =
  'This Investment Policy Statement is generated by an automated algorithm and does not ' +
  'constitute fiduciary investment advice. It is provided for informational and planning ' +
  'purposes only. Past performance is not indicative of future results. Consult a ' +
  'registered investment adviser (RIA) before acting on any recommendation. ' +
  'Investment Advisers Act of 1940, 15 U.S.C. §80b-2(a)(11).';

// VT (Vanguard Total World) CMA benchmarks used for return / Sharpe comparisons
const VT_EXPECTED_RETURN = 0.072;
const VT_SHARPE_ESTIMATE = 0.22;

// ─── Gemini response schema (prose fields only) ───────────────────────────────

const NARRATIVE_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    investmentObjective: {
      type: Type.STRING,
      description:
        '1-2 sentences. Specific — include actual dollar goal, time horizon, and success ' +
        'probability where available. E.g. "Build $1.2M over 22 years targeting 73% success ' +
        'probability, pursuing financial independence through diversified equity growth."',
    },
    liquidityRequirement: {
      type: Type.STRING,
      description:
        '1 sentence. State the required cash reserve based on the client\'s emergency fund ' +
        'status and any planned large expense. Reference actual months or dollars.',
    },
    taxConsiderations: {
      type: Type.STRING,
      description:
        '1-2 sentences. Summarize the client\'s key tax situation: combined marginal rate, ' +
        'state, muni bond suitability, and NIIT exposure if applicable.',
    },
    rebalancingPolicy: {
      type: Type.STRING,
      description:
        '1 sentence. Drift threshold for rebalancing and minimum frequency. ' +
        'E.g. "Rebalance when any holding drifts more than 5% from target; review annually at minimum."',
    },
    reviewSchedule: {
      type: Type.STRING,
      description:
        '1 sentence. Annual review cadence plus triggers for out-of-cycle review ' +
        '(major life event, market drop >20%, income change).',
    },
    maxDrawdownTolerance: {
      type: Type.STRING,
      description:
        '1 sentence. Reference the estimated max drawdown from the portfolio statistics. ' +
        'E.g. "Estimated maximum peak-to-trough drawdown of −28% based on 2008-type stress scenario."',
    },
    concentrationLimit: {
      type: Type.STRING,
      description:
        '1 sentence. Per-position concentration limit inferred from the portfolio. ' +
        'E.g. "No single position exceeds 35% of the portfolio."',
    },
    sequenceRisk: {
      type: Type.STRING,
      description:
        '1 sentence. Sequence-of-returns risk context given the time horizon. ' +
        'For long horizons (>15 years), note low sequence risk; for short (<5 years), flag it.',
    },
    expectedVolatilityNote: {
      type: Type.STRING,
      description:
        '1 sentence. State expected annualized volatility and what a typical drawdown year implies. ' +
        'E.g. "Expected annualized volatility of 14.2% implies a typical bad year of approximately −14%."',
    },
    assetLocationSummary: {
      type: Type.STRING,
      description:
        '2-3 sentences. Summarize the tax-location strategy: which ETFs go in taxable, ' +
        'Roth, traditional/401k — and why. Reference actual tickers and account types.',
    },
    executiveSummary: {
      type: Type.STRING,
      description:
        '2-3 sentences. Overall IPS summary for this client. Cover: risk posture, key tax advantage, ' +
        'goal feasibility verdict, and Critic score interpretation. Reference actual numbers.',
    },
  },
  required: [
    'investmentObjective',
    'liquidityRequirement',
    'taxConsiderations',
    'rebalancingPolicy',
    'reviewSchedule',
    'maxDrawdownTolerance',
    'concentrationLimit',
    'sequenceRisk',
    'expectedVolatilityNote',
    'assetLocationSummary',
    'executiveSummary',
  ],
};

type IPSNarrative = {
  investmentObjective: string;
  liquidityRequirement: string;
  taxConsiderations: string;
  rebalancingPolicy: string;
  reviewSchedule: string;
  maxDrawdownTolerance: string;
  concentrationLimit: string;
  sequenceRisk: string;
  expectedVolatilityNote: string;
  assetLocationSummary: string;
  executiveSummary: string;
};

// ─── Deterministic helpers ────────────────────────────────────────────────────

const BUCKET_DISPLAY: Record<string, string> = {
  safety:      'Safety / Cash',
  growth:      'Growth / Equity',
  income:      'Income / Fixed Income',
  alternative: 'Alternatives / Real Assets',
};

const BUCKET_ORDER = ['safety', 'growth', 'income', 'alternative'];

function buildTargetAllocation(portfolio: Agent3Output): IPSTargetAllocation[] {
  const groups: Record<string, typeof portfolio.allocation> = {};
  for (const slice of portfolio.allocation) {
    if (!groups[slice.category]) groups[slice.category] = [];
    groups[slice.category].push(slice);
  }

  const result: IPSTargetAllocation[] = [];
  for (const cat of BUCKET_ORDER) {
    const slices = groups[cat];
    if (!slices || slices.length === 0) continue;

    const totalWeight = slices.reduce((s, x) => s + x.weight, 0);
    const targetPct = Math.round(totalWeight * 100);

    result.push({
      bucketName: BUCKET_DISPLAY[cat] ?? cat,
      targetPct,
      rangeLow:  Math.max(0, targetPct - 5),
      rangeHigh: Math.min(100, targetPct + 5),
      holdings: slices.map(s => ({
        ticker:           s.ticker,
        name:             ETF_BY_TICKER[s.ticker]?.name ?? s.ticker,
        weight:           Math.round(s.weight * 1000) / 10,
        accountPlacement: s.accountPlacement,
      })),
    });
  }

  return result;
}

// ─── Prompt builder ───────────────────────────────────────────────────────────

function buildPrompt(input: {
  clientProfile:   Agent1Output;
  portfolio:       Agent3Output;
  taxOptimization: Agent5Output;
  criticScore:     Agent6Output;
  intakeAnswers:   IntakeAnswers;
}): string {
  const { clientProfile, portfolio, taxOptimization, criticScore, intakeAnswers } = input;
  const rf = clientProfile.riskProfile;
  const tx = clientProfile.taxProfile;
  const th = clientProfile.timeHorizon;
  const goal = clientProfile.goalAnalysis;
  const stats = portfolio.statistics;

  const holdingsSummary = portfolio.allocation
    .map(s =>
      `  ${s.ticker.padEnd(6)} ${(s.weight * 100).toFixed(1).padStart(5)}%  [${s.category}] → ${s.accountPlacement}`
    )
    .join('\n');

  const topTaxRecs = taxOptimization.recommendations
    .filter(r => r.priority === 'high')
    .slice(0, 4)
    .map(r => `  • ${r.title}: ${r.detail}`)
    .join('\n') || '  None flagged.';

  const restrictions: string[] = [];
  if (clientProfile.investmentPreferences?.esgOnly) restrictions.push('ESG-screened only');
  if (clientProfile.investmentPreferences?.avoidedSectors)
    restrictions.push(`Avoid: ${clientProfile.investmentPreferences.avoidedSectors}`);

  return `You are writing an Investment Policy Statement (IPS) for a specific client.
Write concise, professional prose. No generic disclaimers — reference actual numbers and tickers.

CLIENT PROFILE
══════════════
Risk:          ${rf.riskScore}/10 — ${rf.effectiveRiskTolerance}
Horizon:       ${th.yearsToGoal} years (${th.bucket})${th.isNearDrawdown ? ' — NEAR DRAWDOWN' : ''}
Goal:          ${intakeAnswers.goal}${goal.goalAmount ? ` | target $${goal.goalAmount.toLocaleString()}` : ''}
Feasibility:   ${goal.feasibility} (${(goal.fundedStatus * 100).toFixed(0)}% funded)
Capital:       $${clientProfile.startingCapital.toLocaleString()} lump + $${clientProfile.monthlyContribution.toLocaleString()}/mo
Tax:           ${(tx.federalMarginalRate * 100).toFixed(0)}% federal + ${(tx.stateMarginalRate * 100).toFixed(0)}% state = ${(tx.combinedMarginalRate * 100).toFixed(0)}% combined
State:         ${intakeAnswers.state}
Filing:        ${intakeAnswers.filingStatus}
Accounts:      ${clientProfile.accountStructure.availableAccounts.join(', ')}
Restrictions:  ${restrictions.length > 0 ? restrictions.join('; ') : 'none'}

PORTFOLIO — ${portfolio.allocation.length} ETFs, Sharpe-optimised
══════════════════════════════════════════
${holdingsSummary}

Statistics:
  Expected return:    ${(stats.expectedReturn * 100).toFixed(2)}%
  Expected vol:       ${(stats.expectedVolatility * 100).toFixed(2)}%
  Sharpe ratio:       ${stats.sharpeRatio.toFixed(2)}
  Max drawdown est:   −${(stats.maxDrawdownEstimate * 100).toFixed(1)}%
  Weighted ER:        ${(stats.weightedExpenseRatio * 100).toFixed(3)}%

TOP TAX ACTIONS
═══════════════
${topTaxRecs}
Estimated annual savings: ${taxOptimization.estimatedAnnualSavings} bps

CRITIC SCORE: ${criticScore.scores.overall}/100
  Alignment: ${criticScore.scores.alignment} | Diversification: ${criticScore.scores.diversification} | Tax: ${criticScore.scores.taxEfficiency} | Cost: ${criticScore.scores.costEfficiency} | Risk: ${criticScore.scores.riskManagement}

Write the IPS prose fields for this specific client. Each must reference actual numbers from above.`;
}

// ─── Deterministic narrative fallback ────────────────────────────────────────
//
// Produces all 11 prose fields from templates when GEMINI_API_KEY is absent.
// Every sentence references actual numbers from prior agent outputs so the IPS
// remains informative and client-specific without an LLM call.

function buildDeterministicNarrative(input: {
  clientProfile:   Agent1Output;
  portfolio:       Agent3Output;
  taxOptimization: Agent5Output;
  criticScore:     Agent6Output;
  intakeAnswers:   IntakeAnswers;
}): IPSNarrative {
  const { clientProfile, portfolio, taxOptimization, criticScore, intakeAnswers } = input;
  const rf   = clientProfile.riskProfile;
  const tx   = clientProfile.taxProfile;
  const th   = clientProfile.timeHorizon;
  const goal = clientProfile.goalAnalysis;
  const stats = portfolio.statistics;

  const maxConc = Math.max(...portfolio.allocation.map(s => s.weight));
  const scoreLabel = criticScore.scores.overall >= 90 ? 'excellent' : criticScore.scores.overall >= 80 ? 'strong' : 'acceptable';

  const byPlacement = (acct: string) =>
    portfolio.allocation.filter(s => s.accountPlacement === acct).map(s => s.ticker).join(', ');
  const taxableETFs = byPlacement('taxable');
  const rothETFs    = byPlacement('roth');
  const tradETFs    = byPlacement('traditional');

  const locationParts: string[] = [];
  if (taxableETFs) locationParts.push(`${taxableETFs} in taxable for tax efficiency`);
  if (rothETFs)    locationParts.push(`${rothETFs} in Roth IRA for tax-free compounding`);
  if (tradETFs)    locationParts.push(`${tradETFs} in tax-deferred accounts to reduce current income`);

  return {
    investmentObjective: goal.goalAmount
      ? `Accumulate $${goal.goalAmount.toLocaleString()} over ${th.yearsToGoal} years (${(goal.fundedStatus * 100).toFixed(0)}% currently funded, rated ${goal.feasibility}) through a ${rf.effectiveRiskTolerance} portfolio targeting ${(stats.expectedReturn * 100).toFixed(1)}% expected annual return.`
      : `Maximize portfolio growth over a ${th.yearsToGoal}-year horizon through a ${rf.effectiveRiskTolerance} allocation targeting ${(stats.expectedReturn * 100).toFixed(1)}% expected annual return and a Sharpe ratio of ${stats.sharpeRatio.toFixed(2)}.`,

    liquidityRequirement: intakeAnswers.financialSnapshot?.hasEmergencyFund
      ? `Client maintains an adequate emergency fund outside this portfolio; no additional liquidity sleeve is required.`
      : `A 3–6 month expense reserve is recommended before deploying the full capital; the portfolio assumes this buffer is established separately.`,

    taxConsiderations: `Combined marginal rate of ${(tx.combinedMarginalRate * 100).toFixed(0)}% (${(tx.federalMarginalRate * 100).toFixed(0)}% federal + ${(tx.stateMarginalRate * 100).toFixed(0)}% ${intakeAnswers.state} state). ${tx.combinedMarginalRate >= 0.22 ? 'Tax-exempt municipal bonds are cost-effective at this bracket; VTEB is included where applicable.' : 'Standard broad-market index funds are appropriate at the current tax rate.'}`,

    rebalancingPolicy: `Rebalance when any holding drifts more than 5% from its target weight; conduct a full review at least annually.`,

    reviewSchedule: `Annual review of asset allocation, contributions, and goal feasibility; additional reviews triggered by major life events, income changes >20%, or a market decline exceeding 20%.`,

    maxDrawdownTolerance: `Estimated maximum peak-to-trough drawdown of −${(stats.maxDrawdownEstimate * 100).toFixed(1)}% under a 2008-type stress scenario; the client's risk score of ${rf.riskScore}/10 indicates ${rf.effectiveRiskTolerance} loss tolerance.`,

    concentrationLimit: `No single position exceeds ${(maxConc * 100).toFixed(0)}% of the total portfolio; the ${portfolio.allocation.length}-holding structure limits concentration risk at the security level.`,

    sequenceRisk: th.yearsToGoal >= 15
      ? `With a ${th.yearsToGoal}-year horizon, sequence-of-returns risk is low; early drawdowns have time to recover through continued contributions.`
      : `At ${th.yearsToGoal} years to goal, sequence-of-returns risk warrants monitoring; consider gradually reducing equity exposure as the drawdown date approaches.`,

    expectedVolatilityNote: `Expected annualized volatility of ${(stats.expectedVolatility * 100).toFixed(1)}% implies a typical adverse calendar year of approximately −${(stats.expectedVolatility * 100).toFixed(1)}% to −${(stats.expectedVolatility * 150).toFixed(1)}%.`,

    assetLocationSummary: locationParts.length > 0
      ? `Asset location optimized for after-tax returns: ${locationParts.join('; ')}. This placement targets the estimated ${taxOptimization.estimatedAnnualSavings} bps annual tax alpha.`
      : `All positions placed in taxable accounts; introducing tax-advantaged accounts in future years would improve after-tax compounding.`,

    executiveSummary: `This ${rf.riskScore}/10 risk-score portfolio achieves a ${scoreLabel} Critic score of ${criticScore.scores.overall}/100, with ${(stats.expectedReturn * 100).toFixed(1)}% expected return and a ${stats.sharpeRatio.toFixed(2)} Sharpe ratio. ${goal.goalAmount ? `The $${goal.goalAmount.toLocaleString()} goal is rated ${goal.feasibility} at ${(goal.fundedStatus * 100).toFixed(0)}% funded status.` : ''} Tax optimization targets ${taxOptimization.estimatedAnnualSavings} bps in annual savings through systematic asset location.`,
  };
}

// ─── Shared IPS assembler ─────────────────────────────────────────────────────
//
// Combines the prose narrative (LLM or deterministic) with deterministic
// structured fields to produce the final IPSDocument.

function buildIPSFromNarrative(
  narrative: IPSNarrative,
  input: {
    clientProfile:   Agent1Output;
    portfolio:       Agent3Output;
    taxOptimization: Agent5Output;
    criticScore:     Agent6Output;
    intakeAnswers:   IntakeAnswers;
  },
): IPSDocument {
  const { clientProfile, portfolio, taxOptimization, criticScore, intakeAnswers } = input;
  const tx = clientProfile.taxProfile;

  const muniBondSuitable = tx.combinedMarginalRate >= 0.22;
  const rothConversionOpportunity =
    tx.combinedMarginalRate < 0.22 &&
    clientProfile.accountStructure.availableAccounts.some(a =>
      a.toLowerCase().includes('traditional') || a.toLowerCase().includes('401')
    );
  const annualAUM = clientProfile.startingCapital + clientProfile.monthlyContribution * 12;
  const estimatedAnnualTaxAlpha = Math.round(
    (taxOptimization.estimatedAnnualSavings / 10000) * annualAUM
  );

  const restrictions: string[] = [];
  if (clientProfile.investmentPreferences?.esgOnly) restrictions.push('ESG-screened funds only');
  if (clientProfile.investmentPreferences?.avoidedSectors)
    restrictions.push(`Excluded sectors: ${clientProfile.investmentPreferences.avoidedSectors}`);
  if (clientProfile.investmentPreferences?.favoredSectors)
    restrictions.push(`Tilts toward: ${clientProfile.investmentPreferences.favoredSectors}`);

  return {
    generatedDate: new Date().toISOString(),

    clientProfile: {
      riskScore:             clientProfile.riskProfile.riskScore,
      derivedRiskTolerance:  clientProfile.riskProfile.effectiveRiskTolerance,
      effectiveMarginalRate: tx.combinedMarginalRate,
      horizon:               clientProfile.timeHorizon.yearsToGoal,
      state:                 intakeAnswers.state,
      filingStatus:          intakeAnswers.filingStatus,
      primaryGoal:           intakeAnswers.goal,
      goalAmount:            intakeAnswers.goalAmount,
    },

    investmentObjective: narrative.investmentObjective,

    constraints: {
      liquidityRequirement: narrative.liquidityRequirement,
      taxConsiderations:    narrative.taxConsiderations,
      restrictions,
      rebalancingPolicy:    narrative.rebalancingPolicy,
      reviewSchedule:       narrative.reviewSchedule,
    },

    targetAllocation: buildTargetAllocation(portfolio),

    riskParameters: {
      maxDrawdownTolerance: narrative.maxDrawdownTolerance,
      concentrationLimit:   narrative.concentrationLimit,
      sequenceRisk:         narrative.sequenceRisk,
      expectedVolatility:   narrative.expectedVolatilityNote,
    },

    taxStrategy: {
      assetLocationSummary:   narrative.assetLocationSummary,
      keyTaxActions:          taxOptimization.recommendations
        .filter(r => r.priority === 'high')
        .map(r => r.title),
      estimatedAnnualTaxAlpha,
      rothConversionOpportunity,
      muniBondSuitable,
    },

    benchmarks: {
      primary:                   'VT (Vanguard Total World ETF)',
      secondary:                 'VBINX (Vanguard Balanced Index Fund)',
      expectedReturnVsBenchmark: Math.round(
        (portfolio.statistics.expectedReturn - VT_EXPECTED_RETURN) * 10000
      ) / 100,
      sharpeVsBenchmark: Math.round(
        (portfolio.statistics.sharpeRatio - VT_SHARPE_ESTIMATE) * 100
      ) / 100,
    },

    executiveSummary: narrative.executiveSummary,
    criticScore:      criticScore.scores.overall,
    disclaimer:       DISCLAIMER,
  };
}

// ─── Main agent function ──────────────────────────────────────────────────────

export async function agentIPS(input: {
  clientProfile:   Agent1Output;
  portfolio:       Agent3Output;
  taxOptimization: Agent5Output;
  criticScore:     Agent6Output;
  intakeAnswers:   IntakeAnswers;
}): Promise<IPSDocument | null> {
  const apiKey = process.env.GEMINI_API_KEY ?? process.env.API_KEY;
  if (!apiKey) {
    return buildIPSFromNarrative(buildDeterministicNarrative(input), input);
  }

  const span = tracer.startSpan('llm.ips', {
    attributes: {
      'llm.model':       'gemini-2.5-flash',
      'llm.temperature': 0.2,
      'llm.thinking':    'LOW',
    },
  });

  const startTime = Date.now();
  try {
    const ai = new GoogleGenAI({ apiKey });

    const response = await Promise.race([
      ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: buildPrompt(input),
        config: {
          temperature: 0.2,
          thinkingConfig: { thinkingLevel: ThinkingLevel.LOW },
          responseMimeType: 'application/json',
          responseSchema: NARRATIVE_SCHEMA,
        },
      }),
      new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error('IPS Gemini timeout after 3500ms')), 3500)
      ),
    ]);

    const jsonText = (response.text ?? '').trim();
    if (!jsonText) {
      span.setAttribute('llm.empty_response', true);
      span.end();
      return buildIPSFromNarrative(buildDeterministicNarrative(input), input);
    }

    const executionTimeMs = Date.now() - startTime;
    span.setAttributes({
      'llm.execution_ms':   executionTimeMs,
      'llm.within_sla':     executionTimeMs <= 4000,
      'llm.response_bytes': jsonText.length,
    });
    span.setStatus({ code: SpanStatusCode.OK });
    span.end();

    const narrative = JSON.parse(jsonText) as IPSNarrative;
    return buildIPSFromNarrative(narrative, input);
  } catch (e) {
    span.recordException(e as Error);
    span.setStatus({ code: SpanStatusCode.ERROR, message: e instanceof Error ? e.message : 'IPS generation failed' });
    span.end();
    console.error('[agentIPS] IPS generation failed — falling back to deterministic:', e);
    return buildIPSFromNarrative(buildDeterministicNarrative(input), input);
  }
}
