import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import { createHash } from 'node:crypto';
import { trace, context as otelContext, SpanStatusCode } from '@opentelemetry/api';
import { db } from '@/lib/db';
import { checkRateLimit } from '@/lib/rateLimit';
import { agent1_clientProfile }         from '@/lib/agents/agent1';
import { agent2_economicIntelligence }  from '@/lib/agents/agent2';
import { agent3_portfolioConstruction } from '@/lib/agents/agent3';
import { agent4_riskAnalysis }          from '@/lib/agents/agent4';
import { agent5_taxOptimization }       from '@/lib/agents/agent5';
import { agent6_critic }                from '@/lib/agents/agent6';
import { agent7_synthesis }             from '@/lib/agents/agent7_synthesis';
import { agentIPS }                      from '@/lib/agents/agentIPS';
import { getBaselineSeed, getCandidateSeeds } from '@/lib/agents/baselinePlans';
import { runMonteCarlo }                from '@/lib/monteCarlo/analyticalMonteCarlo';
import type { IPSDocument } from '@/types/index';
import type {
  IntakeAnswers,
  Agent1Output, Agent2Output, Agent3Output,
  Agent4Output, Agent5Output, Agent6Output, Agent7Output,
  MonteCarloOutput,
} from '@/lib/agents/types';

// Vercel function timeout — deterministic pipeline runs well under 5s,
// but keep headroom for Neon cold starts.
export const maxDuration = 60;

const tracer = trace.getTracer('portfolio-agent', '1.0.0');

const DISCLAIMER =
  'This output is generated by an automated algorithm and does not constitute ' +
  'fiduciary investment advice. Past performance is not indicative of future results. ' +
  'Consult a registered investment adviser (RIA) before acting on any recommendation. ' +
  'Source: Investment Advisers Act of 1940, 15 U.S.C. §80b-2(a)(11); ' +
  'SEC Staff Bulletin on Robo-Advisers (2017).';

// ─── V3 plan shape ────────────────────────────────────────────────────────────

interface V3Plan {
  version:         'v3';
  generatedAt:     string;
  disclaimer:      string;
  clientProfile:   Agent1Output;
  economicIntel:   Agent2Output;
  portfolio:       Agent3Output;
  riskAnalysis:    Agent4Output;
  taxOptimization: Agent5Output;
  criticScore:     Agent6Output;
  monteCarlo:      MonteCarloOutput;
  ips?:            IPSDocument;
  synthesis?:      Agent7Output;
}

// ─── L2 plan cache (Neon plan_cache table, 24hr TTL) ─────────────────────────

function planCacheKey(intakeAnswers: IntakeAnswers): string {
  // Date-stamp is YYYY-MM-DD UTC — ensures a cache miss when macro data refreshes
  // (macro cache has a 24hr TTL too, so both caches align). Using UTC date rather
  // than wall-clock prevents the same-inputs run at 23:59 vs 00:01 UTC from hitting
  // different keys; the date only matters for daily cache busting, not precision.
  const date = new Date().toISOString().slice(0, 10);
  const inputHash = createHash('sha256').update(JSON.stringify(intakeAnswers)).digest('hex').slice(0, 16);
  return `plan_v6_${date}_${inputHash}`;
}

async function checkCache(cacheKey: string): Promise<V3Plan | null> {
  try {
    const sql = db();
    const rows = await sql`
      SELECT plan_json FROM plan_cache
      WHERE cache_key = ${cacheKey}
        AND created_at > NOW() - INTERVAL '24 hours'
      LIMIT 1
    ` as Array<{ plan_json: V3Plan }>;
    return rows.length > 0 ? rows[0].plan_json : null;
  } catch {
    return null; // fail open — run pipeline on cache miss
  }
}

function saveCache(cacheKey: string, plan: V3Plan): void {
  void (async () => {
    try {
      const sql = db();
      await sql`
        INSERT INTO plan_cache (cache_key, plan_json, created_at)
        VALUES (${cacheKey}, ${JSON.stringify(plan)}::jsonb, NOW())
        ON CONFLICT (cache_key) DO UPDATE
          SET plan_json = EXCLUDED.plan_json, created_at = EXCLUDED.created_at
      `;
    } catch (e) {
      console.error('[portfolio-agent] cache write failed:', e);
    }
  })();
}

// ─── Intake format normalizer ─────────────────────────────────────────────────
// OnboardingFlow (src/components/planner/) emits the old flat IntakeAnswers shape
// (primaryGoal, hasEmergencyFund at top level). Agents expect the new nested shape
// (goal, financialSnapshot.hasEmergencyFund). Detect by presence of `primaryGoal`.

// Safe numeric coercion — falls back to defaultVal when the input is
// undefined, null, empty, or non-numeric (e.g. Number("abc") → NaN).
function safeNum(val: unknown, defaultVal: number): number {
  const n = Number(val);
  return Number.isFinite(n) ? n : defaultVal;
}

function normalizeIntakeAnswers(raw: unknown): IntakeAnswers {
  const r = raw as Record<string, unknown>;

  // Already new format — pass through as-is
  if (r.goal !== undefined && r.financialSnapshot !== undefined) {
    return r as unknown as IntakeAnswers;
  }

  // Legacy format (pre-OnboardingFlow v2) — coerce into IntakeAnswers shape
  const marketDrop = String(r.marketDropReaction ?? 'passive');
  const riskLevel: 'low' | 'medium' | 'high' =
    marketDrop === 'aggressive' ? 'high' : marketDrop === 'panic' ? 'low' : 'medium';

  const goalAmount = safeNum(r.goalAmount, 0);

  return {
    goal: (r.primaryGoal ?? 'max_growth') as IntakeAnswers['goal'],
    ...(goalAmount > 0 && { goalAmount }),
    timeHorizon:         safeNum(r.yearsUntilWithdrawal, 10),
    startingCapital:     safeNum(r.startingCapital, 0),
    monthlyContribution: safeNum(r.monthlyContribution, 0),
    financialSnapshot: {
      hasEmergencyFund:    Boolean(r.hasEmergencyFund),
      hasHighInterestDebt: String(r.debtLevel ?? '') === 'high',
      ...(r.hasLargeExpense && r.largeExpenseAmount != null
        ? { plannedExpense: safeNum(r.largeExpenseAmount, 0) }
        : {}),
    },
    filingStatus:    (r.taxFilingStatus ?? 'single') as IntakeAnswers['filingStatus'],
    annualIncome:    safeNum(r.annualIncome, 0),
    state:           String(r.state ?? 'CA'),
    age:             safeNum(r.age, 35),
    existingAccounts: { traditional: 0, roth: 0, hsa: 0 },
    riskCapacity:    riskLevel,
    riskWillingness: riskLevel,
    incomeStability: Math.min(5, Math.max(1, safeNum(r.incomeStability, 3))) as IntakeAnswers['incomeStability'],
    availableAccounts: Array.isArray(r.accounts) ? r.accounts as string[] : [],
    ...(r.employerMatchPct != null && { employerMatchPct: safeNum(r.employerMatchPct, 0) }),
    ...(r.favoredSectors != null || r.avoidedSectors != null
      ? {
          investmentPreferences: {
            esgOnly: String(r.favoredSectors ?? '').includes('ESG'),
            ...(r.favoredSectors ? { favoredSectors: String(r.favoredSectors) } : {}),
            ...(r.avoidedSectors ? { avoidedSectors: String(r.avoidedSectors) } : {}),
          },
        }
      : {}),
  };
}

// ─── POST handler ─────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  // Auth + parse before stream opens so HTTP-level errors return non-200
  let intakeAnswers: IntakeAnswers;
  try {
    const body = await req.json();
    intakeAnswers = normalizeIntakeAnswers((body as { answers: unknown }).answers);
    if (!intakeAnswers) return NextResponse.json({ error: 'Missing answers' }, { status: 400 });
  } catch {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
  }

  const { userId } = await auth();
  if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  // 10 plans per user per hour — generous for normal use, blocks abuse
  const withinLimit = await checkRateLimit(userId, 'portfolio-agent', 10, 3600);
  if (!withinLimit) {
    return NextResponse.json(
      { error: 'Rate limit exceeded. You can generate up to 10 plans per hour.' },
      { status: 429 },
    );
  }

  const encoder = new TextEncoder();

  // Paced delay — makes the pipeline feel deliberate to the user while keeping
  // total time to ~10–15s. Each agent "breathes" for a moment after completing
  // so the user sees the progress log fill in step by step.
  const pace = (ms: number) => new Promise<void>(r => setTimeout(r, ms));

  const stream = new ReadableStream({
    async start(controller) {
      const push = (obj: unknown) => {
        try { controller.enqueue(encoder.encode(JSON.stringify(obj) + '\n')); } catch { /* closed */ }
      };
      const log        = (msg: string)                                => push({ type: 'log',        message: msg });
      const agentStart = (agent: string)                              => push({ type: 'agent_start', agent });
      const agentDone  = (agent: string, summary: string, data?: object) => push({ type: 'agent_done',  agent, summary, ...(data ? { data } : {}) });

      // Root span for the entire pipeline run — child spans nest under this.
      const rootSpan = tracer.startSpan('portfolio.pipeline', {
        attributes: { 'user.id': userId },
      });
      const rootCtx = trace.setSpan(otelContext.active(), rootSpan);

      try {
        // ── L2 cache check ────────────────────────────────────────────────────
        const cacheKey = planCacheKey(intakeAnswers);
        rootSpan.setAttribute('intake.cache_key', cacheKey);

        const cacheSpan = tracer.startSpan('cache.plan.check', {}, rootCtx);
        const cached    = await checkCache(cacheKey);
        cacheSpan.setAttribute('cache.hit', cached !== null);
        cacheSpan.end();

        if (cached) {
          log('Loaded from cache.');
          rootSpan.setAttribute('cache.served', true);
          push({ type: 'plan', plan: cached });
          push({ type: 'done' });
          controller.close();
          return;
        }

        const t0 = Date.now();

        // ── Agent 1: Client Profile ───────────────────────────────────────────
        agentStart('clientProfile');
        log('Agent 1/7: Analysing your financial profile...');
        const a1Span = tracer.startSpan('agent.clientProfile', { attributes: { 'agent.sla_ms': 100 } }, rootCtx);
        const clientProfile = agent1_clientProfile({ intakeAnswers });
        a1Span.setAttributes({
          'agent.execution_ms':      clientProfile.executionTimeMs,
          'agent.within_sla':        clientProfile.performance.withinSLA,
          'agent1.risk_score':       clientProfile.riskProfile.riskScore,
          'agent1.goal_feasibility': clientProfile.goalAnalysis.feasibility,
          'agent1.years_to_goal':    clientProfile.timeHorizon.yearsToGoal,
          'agent1.combined_tax_rate': clientProfile.taxProfile.combinedMarginalRate,
        });
        a1Span.end();

        if (clientProfile.constraints.hardStops.length > 0) {
          push({
            type:  'error',
            error: `Portfolio blocked: ${clientProfile.constraints.hardStops.join('; ')}`,
          });
          controller.close();
          return;
        }

        await pace(1200);
        const agent1Summary = `Risk: ${clientProfile.riskProfile.effectiveRiskTolerance} (${clientProfile.riskProfile.riskScore}/10) · Horizon: ${clientProfile.timeHorizon.yearsToGoal}yr · Tax: ${(clientProfile.taxProfile.federalMarginalRate * 100).toFixed(0)}% federal + ${(clientProfile.taxProfile.stateMarginalRate * 100).toFixed(1)}% ${intakeAnswers.state ?? ''}`;
        log(`Profile: risk ${clientProfile.riskProfile.riskScore}/10 | ${clientProfile.timeHorizon.yearsToGoal}yr horizon | ${(clientProfile.taxProfile.combinedMarginalRate * 100).toFixed(0)}% combined tax rate`);
        agentDone('clientProfile', agent1Summary);

        // ── Agent 2: Economic Intelligence ───────────────────────────────────
        await pace(800);
        agentStart('economicIntelligence');
        log('Agent 2/7: Loading live market context from FRED...');
        const a2Span = tracer.startSpan('agent.economicIntelligence', { attributes: { 'agent.sla_ms': 500 } }, rootCtx);
        const economicIntel = await agent2_economicIntelligence({ requestDate: new Date().toISOString() });
        a2Span.setAttributes({
          'agent.execution_ms':    economicIntel.executionTimeMs,
          'agent.within_sla':      economicIntel.performance.withinSLA,
          'agent2.data_source':    economicIntel.dataSource,
          'agent2.regime':         economicIntel.regime.current,
          'agent2.cape':           economicIntel.macroData.shillerCAPE,
          'agent2.data_age_s':     economicIntel.dataAge,
          'agent2.treasury10y':    economicIntel.macroData.treasury10Y,
        });
        a2Span.end();
        await pace(1000);
        const agent2Summary = `Regime: ${economicIntel.regime.current} · Equity: ${economicIntel.assetClassOutlook.equityValuation} (CAPE ${economicIntel.macroData.shillerCAPE}) · Bonds: ${economicIntel.assetClassOutlook.bondOpportunity} · rf ${(economicIntel.assetClassOutlook.riskFreeRate * 100).toFixed(2)}%`;
        log(`Macro: ${economicIntel.regime.current} | 10Y ${(economicIntel.assetClassOutlook.riskFreeRate * 100).toFixed(2)}% | CAPE ${economicIntel.macroData.shillerCAPE} | equity ${economicIntel.assetClassOutlook.equityValuation}`);
        agentDone('economicIntelligence', agent2Summary);

        // ── Agent 3: Portfolio Construction ──────────────────────────────────
        await pace(900);
        agentStart('portfolioConstruction');
        log('Agent 3/7: Running Sharpe optimiser across ETF universe...');
        const baselineSeed = getBaselineSeed(
          clientProfile.riskProfile.riskScore,
          clientProfile.timeHorizon.yearsToGoal,
        );
        const a3Span = tracer.startSpan('agent.portfolioConstruction', { attributes: { 'agent.sla_ms': 30 } }, rootCtx);
        const portfolio = agent3_portfolioConstruction({
          clientProfile,
          economicIntel,
          constructionOverrides: { seedAllocation: baselineSeed },
        });
        a3Span.setAttributes({
          'agent.execution_ms':       portfolio.executionTimeMs,
          'agent.within_sla':         portfolio.performance.withinSLA,
          'agent3.etf_count':         portfolio.allocation.length,
          'agent3.sharpe':            portfolio.statistics.sharpeRatio,
          'agent3.expected_return':   portfolio.statistics.expectedReturn,
          'agent3.expected_vol':      portfolio.statistics.expectedVolatility,
          'agent3.weighted_er':       portfolio.statistics.weightedExpenseRatio,
        });
        a3Span.end();
        await pace(1800);
        const agent3Summary = `${portfolio.allocation.length} ETFs · Expected ${(portfolio.statistics.expectedReturn * 100).toFixed(1)}% return · Vol ${(portfolio.statistics.expectedVolatility * 100).toFixed(1)}% · Sharpe ${portfolio.statistics.sharpeRatio.toFixed(2)}`;
        log(`Portfolio: ${portfolio.allocation.length} holdings | expected return ${(portfolio.statistics.expectedReturn * 100).toFixed(1)}% | Sharpe ${portfolio.statistics.sharpeRatio.toFixed(2)}`);
        agentDone('portfolioConstruction', agent3Summary);

        // ── Agents 4 + 5 in parallel ──────────────────────────────────────────
        await pace(700);
        agentStart('riskAnalysis');
        log('Agent 4/7: Running stress tests and risk analysis...');
        await pace(400);
        agentStart('taxOptimization');
        log('Agent 5/7: Optimising tax placement across accounts...');
        const marketContext = {
          regime:       economicIntel.regime.current,
          cape:         economicIntel.macroData.shillerCAPE,
          riskFreeRate: economicIntel.assetClassOutlook.riskFreeRate,
        };

        const a4Span = tracer.startSpan('agent.riskAnalysis',    { attributes: { 'agent.sla_ms': 10 } }, rootCtx);
        const a5Span = tracer.startSpan('agent.taxOptimization', { attributes: { 'agent.sla_ms': 15 } }, rootCtx);
        const [riskAnalysis, taxOptimization] = await Promise.all([
          Promise.resolve(agent4_riskAnalysis({ portfolio, clientProfile, marketContext })),
          Promise.resolve(agent5_taxOptimization({ portfolio, clientProfile })),
        ]);
        a4Span.setAttributes({
          'agent.execution_ms':        riskAnalysis.executionTimeMs,
          'agent.within_sla':          riskAnalysis.performance.withinSLA,
          'agent4.risk_level':         riskAnalysis.riskLevel,
          'agent4.passes_risk_check':  riskAnalysis.passesRiskCheck,
          'agent4.warning_count':      riskAnalysis.warnings.length,
        });
        a4Span.end();
        a5Span.setAttributes({
          'agent.execution_ms':          taxOptimization.executionTimeMs,
          'agent.within_sla':            taxOptimization.performance.withinSLA,
          'agent5.savings_bps':          taxOptimization.estimatedAnnualSavings,
          'agent5.recommendation_count': taxOptimization.recommendations.length,
          'agent5.tlh_pair_count':       taxOptimization.tlhPairs.length,
        });
        a5Span.end();
        await pace(1400);
        const agent4Summary = `${riskAnalysis.passesRiskCheck ? '✓ Approved' : '✗ Review required'} — ${riskAnalysis.riskLevel} risk · ${riskAnalysis.warnings.length} warning${riskAnalysis.warnings.length !== 1 ? 's' : ''}`;
        log(`Risk: ${riskAnalysis.riskLevel} (${riskAnalysis.warnings.length} warning${riskAnalysis.warnings.length !== 1 ? 's' : ''})`);
        agentDone('riskAnalysis', agent4Summary);
        const agent5Summary = `Est. ${taxOptimization.estimatedAnnualSavings}bps tax alpha · ${taxOptimization.recommendations.length} recommendation${taxOptimization.recommendations.length !== 1 ? 's' : ''} · ${taxOptimization.tlhPairs.length} TLH pair${taxOptimization.tlhPairs.length !== 1 ? 's' : ''}`;
        log(`Tax: ${taxOptimization.estimatedAnnualSavings}bps potential savings identified`);
        agentDone('taxOptimization', agent5Summary);

        // ── Agent 6: Critic ───────────────────────────────────────────────────
        await pace(800);
        agentStart('critic');
        log('Agent 6/7: Scoring portfolio against institutional benchmarks...');
        const a6Span = tracer.startSpan('agent.critic', { attributes: { 'agent.sla_ms': 20 } }, rootCtx);
        const criticScore = agent6_critic({ portfolio, clientProfile, riskAnalysis, taxOptimization, marketContext });
        a6Span.setAttributes({
          'agent.execution_ms':          criticScore.executionTimeMs,
          'agent.within_sla':            criticScore.performance.withinSLA,
          'agent6.score_overall':        criticScore.scores.overall,
          'agent6.score_alignment':      criticScore.scores.alignment,
          'agent6.score_diversification': criticScore.scores.diversification,
          'agent6.score_tax':            criticScore.scores.taxEfficiency,
          'agent6.score_cost':           criticScore.scores.costEfficiency,
          'agent6.score_risk':           criticScore.scores.riskManagement,
          'agent6.passes_threshold':     criticScore.passesThreshold,
        });
        a6Span.end();
        await pace(1200);
        const agent6Summary = `${criticScore.scores.overall}/100 — ${criticScore.passesThreshold ? 'Strong plan' : 'Revision suggested'} · Alignment ${criticScore.scores.alignment} · Risk ${criticScore.scores.riskManagement} · Tax ${criticScore.scores.taxEfficiency}`;
        log(`Score: ${criticScore.scores.overall}/100 — ${criticScore.passesThreshold ? 'APPROVED' : 'review suggested'}`);
        agentDone('critic', agent6Summary);

        // ── Agent 6 improvement loop — two phases ─────────────────────────────
        //
        // Phase 1 — Multi-seed exploration
        //   The Sharpe optimizer is fully deterministic: same seed + same constraints
        //   = identical output every time. Running 5 passes with the same seed only
        //   squeezes constraints on the same local optimum. Instead, we run agent3
        //   from up to 3 genuinely different seed portfolios (primary + adjacent risk
        //   tiers) and let the critic pick the best. Each call is <10ms (pure math).
        //
        // Phase 2 — Targeted refinement (max 2 passes, only if Phase 1 best < 80)
        //   After picking the best candidate, 1–2 targeted constraint passes.
        //   Early exit when the parameter floor is hit (no further change possible).
        let finalPortfolio = portfolio;
        let finalRisk      = riskAnalysis;
        let finalTax       = taxOptimization;
        let finalScore     = criticScore;
        let finalSeed      = baselineSeed;

        const dimLog = (s: typeof criticScore.scores) =>
          `align=${s.alignment} div=${s.diversification} tax=${s.taxEfficiency} cost=${s.costEfficiency} risk=${s.riskManagement}`;
        log(`Critic explore [primary]: ${criticScore.scores.overall}/100 — ${dimLog(criticScore.scores)}`);

        // ── Phase 1: Multi-seed exploration ───────────────────────────────────
        const loopSpan = tracer.startSpan('critic_loop', {
          attributes: { 'loop.initial_score': criticScore.scores.overall },
        }, rootCtx);

        const candidateSeeds = getCandidateSeeds(
          clientProfile.riskProfile.riskScore,
          clientProfile.timeHorizon.yearsToGoal,
        );
        for (const { label, seed } of candidateSeeds) {
          if (label === 'primary') continue; // already scored as first-pass portfolio
          const candidatePortfolio = agent3_portfolioConstruction({
            clientProfile,
            economicIntel,
            constructionOverrides: { seedAllocation: seed },
          });
          const [candidateRisk, candidateTax] = await Promise.all([
            Promise.resolve(agent4_riskAnalysis({ portfolio: candidatePortfolio, clientProfile, marketContext })),
            Promise.resolve(agent5_taxOptimization({ portfolio: candidatePortfolio, clientProfile })),
          ]);
          const candidateScore = agent6_critic({
            portfolio: candidatePortfolio, clientProfile,
            riskAnalysis: candidateRisk, taxOptimization: candidateTax, marketContext,
          });
          loopSpan.addEvent('critic_loop.seed', {
            'loop.phase':       1,
            'loop.seed_label':  label,
            'loop.score':       candidateScore.scores.overall,
            'loop.is_new_best': candidateScore.scores.overall > finalScore.scores.overall,
          });
          log(`Critic explore [${label}]: ${candidateScore.scores.overall}/100 — ${dimLog(candidateScore.scores)}`);
          if (candidateScore.scores.overall > finalScore.scores.overall) {
            finalPortfolio = candidatePortfolio;
            finalRisk      = candidateRisk;
            finalTax       = candidateTax;
            finalScore     = candidateScore;
            finalSeed      = seed;
            log(`Critic: [${label}] is new best — ${candidateScore.scores.overall}/100`);
          }
        }

        // ── Phase 2: Targeted refinement ──────────────────────────────────────
        const MAX_REFINEMENT_PASSES = 3;
        let equityCeiling    = clientProfile.riskProfile.maxEquityAllowed;
        let positionCap      = 0.25;

        for (let pass = 0; pass < MAX_REFINEMENT_PASSES && finalScore.scores.overall < 85; pass++) {
          const s = finalScore.scores;
          const equityPct = finalPortfolio.allocation
            .filter(sl => sl.category === 'growth')
            .reduce((sum, sl) => sum + sl.weight, 0);
          const alignmentFixable =
            (clientProfile.timeHorizon.yearsToGoal < 10 && equityPct > 0.60) ||
            (clientProfile.timeHorizon.isInDrawdownPhase && equityPct > 0.40);

          const fixable = (['alignment', 'diversification', 'riskManagement'] as const)
            .filter(d => d !== 'alignment' || alignmentFixable);
          const strategy = fixable.sort((a, b) => s[a] - s[b])[0] ?? 'diversification';

          const prevEquityCeiling = equityCeiling;
          const prevPositionCap   = positionCap;
          let passClientProfile   = { ...clientProfile };

          if (strategy === 'diversification') {
            positionCap = Math.max(0.12, positionCap - 0.08);
          } else {
            equityCeiling = Math.max(0.20, equityCeiling - 0.10);
            passClientProfile = {
              ...clientProfile,
              riskProfile: { ...clientProfile.riskProfile, maxEquityAllowed: equityCeiling },
            };
          }

          // Early exit: params unchanged means floor was hit — further passes are identical
          if (equityCeiling === prevEquityCeiling && positionCap === prevPositionCap) {
            log(`Critic refinement pass ${pass + 1}: floor hit — stopping early`);
            loopSpan.addEvent('critic_loop.floor_hit', { 'loop.pass': pass + 1 });
            break;
          }

          const passPortfolio = agent3_portfolioConstruction({
            clientProfile: passClientProfile, economicIntel,
            constructionOverrides: { maxEquityWeightPerPosition: positionCap, seedAllocation: finalSeed },
          });
          const [passRisk, passTax] = await Promise.all([
            Promise.resolve(agent4_riskAnalysis({ portfolio: passPortfolio, clientProfile: passClientProfile, marketContext })),
            Promise.resolve(agent5_taxOptimization({ portfolio: passPortfolio, clientProfile: passClientProfile })),
          ]);
          const passScore = agent6_critic({
            portfolio: passPortfolio, clientProfile: passClientProfile,
            riskAnalysis: passRisk, taxOptimization: passTax, marketContext,
          });
          loopSpan.addEvent('critic_loop.refinement', {
            'loop.phase':        2,
            'loop.pass':         pass + 1,
            'loop.strategy':     strategy,
            'loop.score_before': finalScore.scores.overall,
            'loop.score_after':  passScore.scores.overall,
          });
          log(`Critic refinement pass ${pass + 1} [${strategy}]: ${passScore.scores.overall}/100 — ${dimLog(passScore.scores)}`);
          if (passScore.scores.overall > finalScore.scores.overall) {
            finalPortfolio = passPortfolio;
            finalRisk      = passRisk;
            finalTax       = passTax;
            finalScore     = passScore;
          }
        }

        const scoreDelta = finalScore.scores.overall - criticScore.scores.overall;
        loopSpan.setAttributes({
          'loop.final_score':  finalScore.scores.overall,
          'loop.score_delta':  scoreDelta,
          'loop.passes_threshold': finalScore.passesThreshold,
        });
        loopSpan.end();
        log(`Critic loop complete · initial ${criticScore.scores.overall}/100 → final ${finalScore.scores.overall}/100 (${scoreDelta >= 0 ? '+' : ''}${scoreDelta} pts)`);

        if (!finalScore.passesThreshold) {
          const weakest = (['alignment', 'diversification', 'riskManagement', 'taxEfficiency', 'costEfficiency'] as const)
            .reduce((a, b) => finalScore.scores[a] <= finalScore.scores[b] ? a : b);
          log(`Warning: best achievable score is ${finalScore.scores.overall}/100 — below 80/100 quality threshold. Weakest: ${weakest}.`);
          push({ type: 'quality_warning', score: finalScore.scores.overall, threshold: 80, weakestDim: weakest });
        }
        log(`Critic final: ${finalScore.scores.overall}/100 ${finalScore.passesThreshold ? '✓ approved' : '↑ best achievable'}`);

        // ── Monte Carlo ───────────────────────────────────────────────────────
        await pace(600);
        const mcSpan = tracer.startSpan('agent.monteCarlo', {}, rootCtx);
        const monteCarlo = runMonteCarlo(finalPortfolio, clientProfile, clientProfile.timeHorizon.yearsToGoal);
        mcSpan.setAttributes({
          'mc.success_probability': monteCarlo.goalSuccessProbability,
          'mc.p50_final':           monteCarlo.projections.at(-1)?.p50 ?? 0,
        });
        mcSpan.end();
        log(`Monte Carlo: p50 at goal year = $${monteCarlo.projections.at(-1)?.p50.toLocaleString() ?? '—'} | success rate ${(monteCarlo.goalSuccessProbability * 100).toFixed(0)}%`);

        // ── Agents 7a + 7b: IPS Generator + Synthesis in parallel (both Gemini) ──
        await pace(500);
        agentStart('ipsGenerator');
        log('Agent 7a/7: Generating your Investment Policy Statement...');
        agentStart('synthesis');
        log('Agent 7b/7: Writing your personalised investment narrative...');
        const a7aSpan = tracer.startSpan('agent.ipsGenerator', { attributes: { 'agent.sla_ms': 4000, 'llm.model': 'gemini-2.5-flash' } }, rootCtx);
        const a7bSpan = tracer.startSpan('agent.synthesis',    { attributes: { 'agent.sla_ms': 5000, 'llm.model': 'gemini-2.5-flash' } }, rootCtx);
        const [ips, synthesis] = await Promise.all([
          agentIPS({
            clientProfile,
            portfolio:       finalPortfolio,
            taxOptimization: finalTax,
            criticScore:     finalScore,
            intakeAnswers,
          }),
          agent7_synthesis({
            clientProfile,
            economicIntel,
            portfolio:       finalPortfolio,
            riskAnalysis:    finalRisk,
            taxOptimization: finalTax,
            criticScore:     finalScore,
          }),
        ]);
        a7aSpan.setAttributes({
          'agent.success': ips !== null,
          ...(ips ? { 'agent.execution_ms': Date.now() - t0 } : {}),
        });
        a7aSpan.end();
        a7bSpan.setAttributes({
          'agent.success':      synthesis !== null,
          'agent.used_fallback': synthesis?.usedFallback ?? false,
          ...(synthesis ? {
            'agent.execution_ms':      synthesis.executionTimeMs,
            'agent.within_sla':        synthesis.performance.withinSLA,
            'llm.narrative_length':    synthesis.portfolioNarrative.length,
            'llm.key_insights_count':  synthesis.keyInsights.length,
          } : {}),
        });
        a7bSpan.end();
        if (ips) {
          const ipsSum = `Investment Policy Statement generated — ${finalScore.scores.overall}/100 Critic score`;
          log(`IPS: ${ipsSum}`);
          agentDone('ipsGenerator', ipsSum);
          push({ type: 'ips', ips });
        } else {
          log('IPS: skipped (GEMINI_API_KEY not set)');
          agentDone('ipsGenerator', 'Skipped — GEMINI_API_KEY not set');
        }
        if (synthesis) {
          log(`Narrative: generated in ${synthesis.executionTimeMs}ms`);
          agentDone('synthesis', `Investment narrative generated in ${synthesis.executionTimeMs}ms`);
        } else {
          log('Narrative: skipped (GEMINI_API_KEY not set)');
          agentDone('synthesis', 'Skipped — GEMINI_API_KEY not set');
        }

        // ── Assemble + stream plan ────────────────────────────────────────────
        const plan: V3Plan = {
          version:         'v3',
          generatedAt:     new Date().toISOString(),
          disclaimer:      DISCLAIMER,
          clientProfile,
          economicIntel,
          portfolio:       finalPortfolio,
          riskAnalysis:    finalRisk,
          taxOptimization: finalTax,
          criticScore:     finalScore,
          monteCarlo,
          ...(ips       ? { ips }       : {}),
          ...(synthesis ? { synthesis } : {}),
        };

        const durationMs = Date.now() - t0;
        console.log(JSON.stringify({
          stage:     'pipeline_complete',
          durationMs,
          score:     finalScore.scores.overall,
          riskLevel: finalRisk.riskLevel,
          withinSLA: durationMs < 18000,
        }));
        rootSpan.setAttributes({
          'pipeline.duration_ms':    durationMs,
          'pipeline.final_score':    finalScore.scores.overall,
          'pipeline.risk_level':     finalRisk.riskLevel,
          'pipeline.within_sla':     durationMs < 18000,
          'pipeline.cache_served':   false,
        });
        rootSpan.setStatus({ code: SpanStatusCode.OK });

        push({ type: 'plan', plan });

        // ── Cache write (fire-and-forget) ─────────────────────────────────────
        saveCache(cacheKey, plan);

        push({ type: 'done' });
        controller.close();

      } catch (e: unknown) {
        rootSpan.recordException(e as Error);
        rootSpan.setStatus({ code: SpanStatusCode.ERROR, message: e instanceof Error ? e.message : 'Server error' });
        console.error('[POST /api/portfolio-agent]', e);
        push({ type: 'error', error: e instanceof Error ? e.message : 'Server error' });
        try { controller.close(); } catch { /* already closed */ }
      } finally {
        rootSpan.end();
      }
    },
  });

  return new Response(stream, {
    headers: {
      'Content-Type': 'application/x-ndjson',
      'Cache-Control': 'no-cache',
      'X-Accel-Buffering': 'no', // disable Vercel/nginx buffering — flush chunks immediately
    },
  });
}
